import "./globals.css";
import WalletConnectSetup from "@/components/WalletConnectSetup";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <WalletConnectSetup>{children}</WalletConnectSetup>
      </body>
    </html>
  );
}
